[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders"
  status = 200

[[redirects]]
  from = "/api/order-update"
  to = "/.netlify/functions/order-update"
  status = 200
